version: "3"
services:
  my_postgres:
    image: postgres:14
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  etl_project:
    image: nxbfuentes/openskyflights_etl:1.0
    depends_on:
      - my_postgres
    env_file:
      - .env
